# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under zhe_bugbash/databricks-resources/*
# and zhe_bugbash/bundle.yml with prod environment configs,
# when PRs are merged into the release branch
name: Bundle Deployment for zhe-bugbash Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./zhe_bugbash

env:
  ARM_TENANT_ID: ${{ secrets.PROD_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.PROD_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.PROD_AZURE_SP_CLIENT_SECRET }}

jobs:
  prod:
    concurrency: zhe-bugbash-prod-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Prod Environment
        id: validate
        run: |
          databricks bundle validate -e prod
      - name: Deploy Bundle to Prod Environment
        id: deploy
        run: |
          databricks bundle deploy -e prod
