# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under zhe_bugbash/databricks-resources/*
# and zhe_bugbash/bundle.yml with staging environment configs,
# when PRs are merged into the default branch
name: Bundle Deployment for zhe-bugbash Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./zhe_bugbash

env:
  ARM_TENANT_ID: ${{ secrets.STAGING_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}

jobs:
  staging:
    concurrency: zhe-bugbash-staging-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Staging Environment
        id: validate
        run: |
          databricks bundle validate -e staging
      - name: Deploy Bundle to Staging Environment
        id: deploy
        run: |
          databricks bundle deploy -e staging
